/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo.o5cinema;

import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.text.DateFormat;
import java.io.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
/**
 *
 * @author HP
 */
public class TiketBioskop extends javax.swing.JFrame {
    String [][] purchasesave = new String [4][1];
    double overralltotalsale = 0;
    int jumlahDewasa = 0;
    int ps =0;
    String password;
    String cekpassword = "kosonginaja";
    String film;
    String tanggal;
    String waktu;
    String tiket;
    String kursi;
    String kursi2;
    
    /**
     * Creates new form TiketBioskop
     */
    public TiketBioskop() {
        initComponents();
        tampil_combo();
        this.setLocationRelativeTo(null);// center form in the screen
        DateFormat dateFormat = new SimpleDateFormat("EEEE, dd MMMMM, yyyy");
        Date date = new Date();
        lblmaindate.setText(dateFormat.format(date));
    }
    
    public void tampil_combo(){
        try{
            String sql = "select * from film";
            java.sql.Connection conn = (Connection)KoneksiDB.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                cmbfilm.addItem(rs.getString("nama_film"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbfilm = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTanggal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbWaktu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbDewasa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblsubtotal = new javax.swing.JLabel();
        lblPajak = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        btnBaru = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnDetailPembelian = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblNamaFilm = new javax.swing.JLabel();
        lblJumTikDewasa = new javax.swing.JLabel();
        lblTgldanWaktu = new javax.swing.JLabel();
        lblTotalBayar = new javax.swing.JLabel();
        btnTagihan = new javax.swing.JButton();
        lblmaindate = new javax.swing.JLabel();
        cmbKursi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbKursi2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(952, 606));

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("         5O5 CINEMA");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pilih Film");

        cmbfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbfilmActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Tanggal dan Waktu");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal ");

        cmbTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin, 23 Januari 2023", "Selasa, 24 Januari 2023", "Rabu, 25 Januari 2023", "Kamis, 26 Januari 2023", "Jumat, 27 Januari 2023", "Sabtu, 28 Januari 2023", "Minggu, 29 Januari 2023", "Senin, 30 Januari 2023", "Selasa, 31 Januari 2023", "Rabu, 1 Februari 2023", " " }));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Waktu");

        cmbWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11.00", "15.00", "17.00", "19.00", "21.00" }));

        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Jumlah Tiket dan Nomor Kursi");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah");

        cmbDewasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDewasaActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sub Total");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pajak (2%)");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total");

        lblsubtotal.setForeground(new java.awt.Color(255, 255, 255));
        lblsubtotal.setText("0");

        lblPajak.setForeground(new java.awt.Color(255, 255, 255));
        lblPajak.setText("0");

        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0");

        btnBaru.setBackground(new java.awt.Color(255, 255, 153));
        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(255, 255, 153));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnDetailPembelian.setBackground(new java.awt.Color(255, 255, 153));
        btnDetailPembelian.setText("Beli");
        btnDetailPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailPembelianActionPerformed(evt);
            }
        });

        btnCetak.setBackground(new java.awt.Color(255, 255, 153));
        btnCetak.setText("Cetak Tiket");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnBayar.setBackground(new java.awt.Color(255, 255, 153));
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 255, 153));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nama Film");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jumlah | No. Kursi");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tanggal dan Waktu");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total Bayar");

        lblNamaFilm.setBackground(new java.awt.Color(255, 255, 255));
        lblNamaFilm.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaFilm.setText("-");

        lblJumTikDewasa.setForeground(new java.awt.Color(255, 255, 255));
        lblJumTikDewasa.setText("-");

        lblTgldanWaktu.setForeground(new java.awt.Color(255, 255, 255));
        lblTgldanWaktu.setText("-");

        lblTotalBayar.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalBayar.setText("-");

        btnTagihan.setBackground(new java.awt.Color(255, 255, 153));
        btnTagihan.setText("Tagihan");
        btnTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagihanActionPerformed(evt);
            }
        });

        cmbKursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));
        cmbKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKursiActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kursi");

        cmbKursi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbKursi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKursi2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(lblmaindate)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbTanggal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbWaktu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbDewasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbKursi2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotal))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPajak))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(38, 38, 38)
                                        .addComponent(lblsubtotal))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(lblimage))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTgldanWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblJumTikDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnTagihan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblNamaFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnBaru)
                .addGap(88, 88, 88)
                .addComponent(btnHitung)
                .addGap(78, 78, 78)
                .addComponent(btnDetailPembelian)
                .addGap(98, 98, 98)
                .addComponent(btnCetak)
                .addGap(93, 93, 93)
                .addComponent(btnBayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexit)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbfilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(lblmaindate)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(cmbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cmbDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKursi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblimage)
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblsubtotal))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblPajak))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTotal))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBaru)
                    .addComponent(btnHitung)
                    .addComponent(btnDetailPembelian)
                    .addComponent(btnCetak)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBayar)
                        .addComponent(btnexit)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaFilm)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumTikDewasa)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblTgldanWaktu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblTotalBayar))
                .addGap(18, 18, 18)
                .addComponent(btnTagihan)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbfilmActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbfilmActionPerformed

    private void btnTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagihanActionPerformed
        // TODO add your handling code here:
        DecimalFormat formatter = new DecimalFormat("Rp ");
        JOptionPane.showMessageDialog(null,"Tiket Bayar\n\n Dewasa: "+Integer.toString(jumlahDewasa)+"\n\nTotal Bayar: "+formatter.format(overralltotalsale));
    }//GEN-LAST:event_btnTagihanActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        final double TikDewasa = 40000;
        double subtotal = 0;
        double subtotalDewasa = 0;
        double pajak = 0;
        double total = 0;

        DecimalFormat formatter = new DecimalFormat("Rp ");

        String adultstring = (String)cmbDewasa.getSelectedItem();
        

        int adult = Integer.parseInt(adultstring);
       
        subtotalDewasa = adult * TikDewasa;
        subtotal = subtotalDewasa;
        pajak = 0.02*subtotal;

        total = pajak + subtotal;

        lblsubtotal.setText(formatter.format(subtotal));
        lblPajak.setText(formatter.format(pajak));
        lblTotal .setText(formatter.format(total));

        overralltotalsale = overralltotalsale+total;
        jumlahDewasa = jumlahDewasa + Integer.parseInt((String)cmbDewasa.getSelectedItem());
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnDetailPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailPembelianActionPerformed
        // TODO add your handling code here:
        jumlahDewasa = Integer.parseInt((String) cmbDewasa.getSelectedItem());
        lblNamaFilm.setText((String)cmbfilm.getSelectedItem());
        lblJumTikDewasa.setText((String)cmbDewasa.getSelectedItem()+" | "+cmbKursi.getSelectedItem()+" "+cmbKursi2.getSelectedItem());
        lblTgldanWaktu.setText((String)cmbTanggal.getSelectedItem()+ " | " + (String)cmbWaktu.getSelectedItem());
        lblTotalBayar.setText(lblTotal.getText());

        purchasesave[0][0] = "Nama Film: " + (String)cmbfilm.getSelectedItem();
        purchasesave[1][0] = "Tiket Dewasa | No. Kursi: "+(String)cmbDewasa.getSelectedItem()+" | "+cmbKursi.getSelectedItem()+cmbKursi2.getSelectedItem();
        purchasesave[2][0] = "Tanggal dan Waktu: "+(String)cmbTanggal.getSelectedItem()+ " | " +(String)cmbWaktu.getSelectedItem();
        purchasesave[3][0] = "Total Bayar: "+lblTotal.getText();
        
        try {
            Connection conn = KoneksiDB.getKoneksi();
            
            String sql = "INSERT INTO pembelian (film, tanggal, waktu, tik_dewasa, total_bayar) VALUES (?,?,?,?,?)";
            
            PreparedStatement p = conn.prepareStatement(sql);
            
            p.setString (1, (String)cmbfilm.getSelectedItem());
            p.setString (2, (String)cmbTanggal.getSelectedItem());
            p.setString (3, (String)cmbWaktu.getSelectedItem());
            p.setInt (4, Integer.parseInt((String) cmbDewasa.getSelectedItem()));
            p.setString (5, lblTotal.getText());
            
            p.executeUpdate();
            p.close();
        } catch (SQLException e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_btnDetailPembelianActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        film = cmbfilm.getSelectedItem().toString();
        tanggal = cmbTanggal.getSelectedItem().toString();
        waktu = cmbWaktu.getSelectedItem().toString();
        tiket = cmbDewasa.getSelectedItem().toString();
        kursi = cmbKursi.getSelectedItem().toString();
        kursi2 = cmbKursi2.getSelectedItem().toString();
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter("movie.txt",true));
            out.newLine();
            for(int i=0;i<4;i++)
            {
                out.write(purchasesave[i][0]);
                out.newLine();
            }

            out.close();

            JOptionPane.showMessageDialog(null,"Nama Film : "+film+"\nJumlah Tiket : "+tiket+"\nNo. Kursi : "+kursi+kursi2+"\nTanggal : "+tanggal+"\nWaktu : "+waktu);
        }
        catch (IOException e)
        {
            System.out.println("Gagal");
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        lblNamaFilm.setText(" ");
        lblJumTikDewasa.setText(" ");
        lblTgldanWaktu.setText(" ");
        lblTotalBayar.setText(" ");
        cmbfilm.setSelectedIndex(0);
        cmbDewasa.setSelectedIndex(0);
        cmbTanggal.setSelectedIndex(0);
        cmbWaktu.setSelectedIndex(0);
        lblTotal.setText("0");
        lblPajak.setText("0");
        lblsubtotal.setText("0");
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        ps = Integer.parseInt(JOptionPane.showInputDialog(null,"Masukkan nomor virtual account Anda"));
         password = JOptionPane.showInputDialog(null,"Password");
        if (password.equals(cekpassword))
            JOptionPane.showMessageDialog(null, "Pembayaran Sukses");
        else
            JOptionPane.showMessageDialog(null,"Password Salah");
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void cmbDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDewasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDewasaActionPerformed

    private void cmbKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKursiActionPerformed

    private void cmbKursi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKursi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKursi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketBioskop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDetailPembelian;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnTagihan;
    private javax.swing.JButton btnexit;
    private javax.swing.JComboBox<String> cmbDewasa;
    private javax.swing.JComboBox<String> cmbKursi;
    private javax.swing.JComboBox<String> cmbKursi2;
    private javax.swing.JComboBox<String> cmbTanggal;
    private javax.swing.JComboBox<String> cmbWaktu;
    private javax.swing.JComboBox<String> cmbfilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJumTikDewasa;
    private javax.swing.JLabel lblNamaFilm;
    private javax.swing.JLabel lblPajak;
    private javax.swing.JLabel lblTgldanWaktu;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalBayar;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblmaindate;
    private javax.swing.JLabel lblsubtotal;
    // End of variables declaration//GEN-END:variables
}
